def anu():
    print("you choice " )
    print(" january ")
    print(" Februry ")
    print(" March ")
    print(" April ")
    print(" May ")
    print(" June ")
    print(" July ")
    print(" Auguest")
    print(" September")
    print(" October ")
    print(" November ")
    print(" December ")

anu()
print("")
anu()